program: src/project/train.py
method: random
metric:
  name: validation/loss
  goal: minimize

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.05
  batch_size:
    values: [16,32, 64]
  epochs:
    values: [5,10,15]
  num_workers:
    value: 2

command:
  - uv
  - run
  - invoke
  - train
